In [1]:
import pandas as pd

1.	Create a DataFrame
o	Create a DataFrame containing student names, roll numbers, branch, and marks.
o	Display the first 5 and last 5 records.

In [2]:
df=pd.DataFrame({"name":["anmol","raghav","shyam","hari","gopal","hareesh","naman","krishna","suman"],
                 "roll_numbers":[3,5,6,8,7,4,7,8,6],
                 "branch":["cse","aiml","cse","aiml","mechanical","cse","aiml","mechanical","aiml"],
                 "marks":[45,23,42,45,34,45,56,56,67]})
df.head()

     name  roll_numbers      branch  marks
0   anmol             3         cse     45
1  raghav             5        aiml     23
2   shyam             6         cse     42
3    hari             8        aiml     45
4   gopal             7  mechanical     34

In [3]:
df.tail()

      name  roll_numbers      branch  marks
4    gopal             7  mechanical     34
5  hareesh             4         cse     45
6    naman             7        aiml     56
7  krishna             8  mechanical     56
8    suman             6        aiml     67

2.	Series Operations
o	Create a Pandas Series containing marks of 10 students.
o	Find the maximum, minimum, mean, and median marks.

In [4]:
marks=pd.Series([34,56,45,345,46,55,4,5,55,6])
marks,marks.max(),marks.mean(),marks.min(),marks.median()

(0     34
 1     56
 2     45
 3    345
 4     46
 5     55
 6      4
 7      5
 8     55
 9      6
 dtype: int64,
 np.int64(345),
 np.float64(65.1),
 np.int64(4),
 np.float64(45.5))

3.	DataFrame Information
o	Create a DataFrame with employee details.
o	Display its shape, columns, data types, and statistical summary.

In [5]:
employee=pd.DataFrame({"e_id":[2,4,5,7,8,7,5,3,4,6],
                       "e_name":["a","b","c","d","e","f","g","h","i","j"],
                       "salary":[3400,5677,3556,6757,464,5566,4545,6768,4455,3434]})
employee

   e_id e_name  salary
0     2      a    3400
1     4      b    5677
2     5      c    3556
3     7      d    6757
4     8      e     464
5     7      f    5566
6     5      g    4545
7     3      h    6768
8     4      i    4455
9     6      j    3434

In [6]:
employee.describe()

            e_id       salary
count  10.000000    10.000000
mean    5.100000  4462.200000
std     1.911951  1893.735509
min     2.000000   464.000000
25%     4.000000  3464.500000
50%     5.000000  4500.000000
75%     6.750000  5649.250000
max     8.000000  6768.000000

In [7]:
employee.size

30

In [8]:
employee.columns

Index(['e_id', 'e_name', 'salary'], dtype='object')

In [9]:
employee.dtypes

e_id       int64
e_name    object
salary     int64
dtype: object

In [10]:
employee.shape

(10, 3)

o	Given a student DataFrame, select only Name, Branch, and Marks columns.

In [11]:
student = pd.DataFrame({
    "Roll_No": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                111, 112, 113, 114, 115, 116, 117, 118, 119, 120],

    "Name": ["Anmol", "Rahul", "Priya", "Aman", "Neha",
             "Riya", "Karan", "Simran", "Arjun", "Pooja",
             "Vikas", "Sneha", "Rohit", "Kavya", "Yash",
             "Nisha", "Mohit", "Divya", "Harsh", "Isha"],

    "Age": [20, 21, 19, 22, 20,
            21, 23, 20, 22, 19,
            21, 20, 22, 23, 19,
            21, 20, 22, 23, 19],

    "Branch": ["CSE", "IT", "ECE", "ME", "CSE",
               "IT", "AIML", "ECE", "ME", "AIML",
               "CSE", "IT", "ECE", "ME", "AIML",
               "CSE", "IT", "ECE", "ME", "AIML"],

    "Semester": [3, 3, 2, 4, 3,
                 3, 5, 2, 4, 5,
                 4, 2, 3, 5, 4,
                 6, 5, 2, 4, 3],

    "Marks": [85, 78, 92, 67, 88,
              81, 95, 74, 69, 90,
              76, 84, 91, 73, 89,
              80, 94, 77, 68, 86],

    "City": ["Delhi", "Mathura", "Agra", "Noida", "Meerut",
             "Lucknow", "Kanpur", "Jaipur", "Gurgaon", "Pune",
             "Varanasi", "Patna", "Bhopal", "Indore", "Chandigarh",
             "Dehradun", "Surat", "Ahmedabad", "Mumbai", "Hyderabad"]
})

print(student)

    Roll_No    Name  Age Branch  Semester  Marks        City
0       101   Anmol   20    CSE         3     85       Delhi
1       102   Rahul   21     IT         3     78     Mathura
2       103   Priya   19    ECE         2     92        Agra
3       104    Aman   22     ME         4     67       Noida
4       105    Neha   20    CSE         3     88      Meerut
5       106    Riya   21     IT         3     81     Lucknow
6       107   Karan   23   AIML         5     95      Kanpur
7       108  Simran   20    ECE         2     74      Jaipur
8       109   Arjun   22     ME         4     69     Gurgaon
9       110   Pooja   19   AIML         5     90        Pune
10      111   Vikas   21    CSE         4     76    Varanasi
11      112   Sneha   20     IT         2     84       Patna
12      113   Rohit   22    ECE         3     91      Bhopal
13      114   Kavya   23     ME         5     73      Indore
14      115    Yash   19   AIML         4     89  Chandigarh
15      116   Nisha   21    CSE         6     80    Dehradun
16      117   Mohit   20     IT         5     94       Surat
17      118   Divya   22    ECE         2     77   Ahmedabad
18      119   Harsh   23     ME         4     68      Mumbai
19      120    Isha   19   AIML         3     86   Hyderabad

In [12]:
print(student[["Name", "Marks","Branch"]])

      Name  Marks Branch
0    Anmol     85    CSE
1    Rahul     78     IT
2    Priya     92    ECE
3     Aman     67     ME
4     Neha     88    CSE
5     Riya     81     IT
6    Karan     95   AIML
7   Simran     74    ECE
8    Arjun     69     ME
9    Pooja     90   AIML
10   Vikas     76    CSE
11   Sneha     84     IT
12   Rohit     91    ECE
13   Kavya     73     ME
14    Yash     89   AIML
15   Nisha     80    CSE
16   Mohit     94     IT
17   Divya     77    ECE
18   Harsh     68     ME
19    Isha     86   AIML

5.	Selecting Rows
o	Extract the first 10 rows from index 5 to 15 using iloc.

In [13]:
student.iloc[:10]

   Roll_No    Name  Age Branch  Semester  Marks     City
0      101   Anmol   20    CSE         3     85    Delhi
1      102   Rahul   21     IT         3     78  Mathura
2      103   Priya   19    ECE         2     92     Agra
3      104    Aman   22     ME         4     67    Noida
4      105    Neha   20    CSE         3     88   Meerut
5      106    Riya   21     IT         3     81  Lucknow
6      107   Karan   23   AIML         5     95   Kanpur
7      108  Simran   20    ECE         2     74   Jaipur
8      109   Arjun   22     ME         4     69  Gurgaon
9      110   Pooja   19   AIML         5     90     Pune

In [14]:
student.iloc[5:16]

    Roll_No    Name  Age Branch  Semester  Marks        City
5       106    Riya   21     IT         3     81     Lucknow
6       107   Karan   23   AIML         5     95      Kanpur
7       108  Simran   20    ECE         2     74      Jaipur
8       109   Arjun   22     ME         4     69     Gurgaon
9       110   Pooja   19   AIML         5     90        Pune
10      111   Vikas   21    CSE         4     76    Varanasi
11      112   Sneha   20     IT         2     84       Patna
12      113   Rohit   22    ECE         3     91      Bhopal
13      114   Kavya   23     ME         5     73      Indore
14      115    Yash   19   AIML         4     89  Chandigarh
15      116   Nisha   21    CSE         6     80    Dehradun

6.	Using loc
o	Set the student roll number as the index.
o	Select students with specific roll numbers using loc.

In [15]:
studetn.loc[]

SyntaxError: invalid syntax (2856299853.py, line 1)

7.	Filtering Data
o	Find all students who scored more than 75 marks.

In [ ]:
student[student["Marks"] > 75]

    Roll_No   Name  Age Branch  Semester  Marks        City
0       101  Anmol   20    CSE         3     85       Delhi
1       102  Rahul   21     IT         3     78     Mathura
2       103  Priya   19    ECE         2     92        Agra
4       105   Neha   20    CSE         3     88      Meerut
5       106   Riya   21     IT         3     81     Lucknow
6       107  Karan   23   AIML         5     95      Kanpur
9       110  Pooja   19   AIML         5     90        Pune
10      111  Vikas   21    CSE         4     76    Varanasi
11      112  Sneha   20     IT         2     84       Patna
12      113  Rohit   22    ECE         3     91      Bhopal
14      115   Yash   19   AIML         4     89  Chandigarh
15      116  Nisha   21    CSE         6     80    Dehradun
16      117  Mohit   20     IT         5     94       Surat
17      118  Divya   22    ECE         2     77   Ahmedabad
19      120   Isha   19   AIML         3     86   Hyderabad

8.	Multiple Conditions
o	Find students from the CSE branch who scored more than 80.

In [ ]:
student[(student["Marks"]>80) & (student["Branch"]== "CSE")]

   Roll_No   Name  Age Branch  Semester  Marks    City
0      101  Anmol   20    CSE         3     85   Delhi
4      105   Neha   20    CSE         3     88  Meerut

9.	Adding a Column
o	Add a Result column based on marks:
	Marks ≥ 40 → Pass
	Marks < 40 → Fail

In [ ]:
student["Grade"] = ""
student.loc[student["Marks"]>=80, "Grade"] = "Pass"
student.loc[student["Marks"]<80, "Grade"]= "Fail"

In [ ]:
student

    Roll_No    Name  Age Branch  Semester  Marks        City Grade
0       101   Anmol   20    CSE         3     85       Delhi  Pass
1       102   Rahul   21     IT         3     78     Mathura  Fail
2       103   Priya   19    ECE         2     92        Agra  Pass
3       104    Aman   22     ME         4     67       Noida  Fail
4       105    Neha   20    CSE         3     88      Meerut  Pass
5       106    Riya   21     IT         3     81     Lucknow  Pass
6       107   Karan   23   AIML         5     95      Kanpur  Pass
7       108  Simran   20    ECE         2     74      Jaipur  Fail
8       109   Arjun   22     ME         4     69     Gurgaon  Fail
9       110   Pooja   19   AIML         5     90        Pune  Pass
10      111   Vikas   21    CSE         4     76    Varanasi  Fail
11      112   Sneha   20     IT         2     84       Patna  Pass
12      113   Rohit   22    ECE         3     91      Bhopal  Pass
13      114   Kavya   23     ME         5     73      Indore  Fail
14      115    Yash   19   AIML         4     89  Chandigarh  Pass
15      116   Nisha   21    CSE         6     80    Dehradun  Pass
16      117   Mohit   20     IT         5     94       Surat  Pass
17      118   Divya   22    ECE         2     77   Ahmedabad  Fail
18      119   Harsh   23     ME         4     68      Mumbai  Fail
19      120    Isha   19   AIML         3     86   Hyderabad  Pass

10.	Sorting Data
o	Sort students by marks in descending order.
o	Display the top 5 students.

In [ ]:
descending=student.sort_values(by="Marks", ascending=False)
descending.head()

    Roll_No   Name  Age Branch  Semester  Marks    City Grade
6       107  Karan   23   AIML         5     95  Kanpur  Pass
16      117  Mohit   20     IT         5     94   Surat  Pass
2       103  Priya   19    ECE         2     92    Agra  Pass
12      113  Rohit   22    ECE         3     91  Bhopal  Pass
9       110  Pooja   19   AIML         5     90    Pune  Pass

11.	Missing Values
o	Create a DataFrame containing missing values.
o	Identify missing values using isnull() and isna().

In [ ]:
dataset=pd.DataFrame({
    "name":["anmol", "nama", "rajesh", "gauri", "keshav", "kapil", "srishti", "vaibhav", "dharmensh","hari", "raghav", "suman"],
    "class":[12,11,5,3,5,None,8,8,None,7,None,8],
    "Marks":[90,56,None, 23, 45, 67, None, 34, 34, None,56,None],
    "Age": [21,3,4,6,None,56,34,5,23,34,None,None]
})

In [ ]:
dataset

         name  class  Marks   Age
0       anmol   12.0   90.0  21.0
1        nama   11.0   56.0   3.0
2      rajesh    5.0    NaN   4.0
3       gauri    3.0   23.0   6.0
4      keshav    5.0   45.0   NaN
5       kapil    NaN   67.0  56.0
6     srishti    8.0    NaN  34.0
7     vaibhav    8.0   34.0   5.0
8   dharmensh    NaN   34.0  23.0
9        hari    7.0    NaN  34.0
10     raghav    NaN   56.0   NaN
11      suman    8.0    NaN   NaN

In [ ]:
dataset.isna()

     name  class  Marks    Age
0   False  False  False  False
1   False  False  False  False
2   False  False   True  False
3   False  False  False  False
4   False  False  False   True
5   False   True  False  False
6   False  False   True  False
7   False  False  False  False
8   False   True  False  False
9   False  False   True  False
10  False   True  False   True
11  False  False   True   True

In [ ]:
dataset.isnull()

     name  class  Marks    Age
0   False  False  False  False
1   False  False  False  False
2   False  False   True  False
3   False  False  False  False
4   False  False  False   True
5   False   True  False  False
6   False  False   True  False
7   False  False  False  False
8   False   True  False  False
9   False  False   True  False
10  False   True  False   True
11  False  False   True   True

12.	Handling Missing Values
o	Replace missing numerical values with the column mean.

In [ ]:
dataset.fillna({
    "Marks": dataset["Marks"].mean(),
    "Age": dataset["Age"].mean()
})

         name  class   Marks        Age
0       anmol   12.0  90.000  21.000000
1        nama   11.0  56.000   3.000000
2      rajesh    5.0  50.625   4.000000
3       gauri    3.0  23.000   6.000000
4      keshav    5.0  45.000  20.666667
5       kapil    NaN  67.000  56.000000
6     srishti    8.0  50.625  34.000000
7     vaibhav    8.0  34.000   5.000000
8   dharmensh    NaN  34.000  23.000000
9        hari    7.0  50.625  34.000000
10     raghav    NaN  56.000  20.666667
11      suman    8.0  50.625  20.666667

In [ ]:
dataset

         name  class   Marks        Age
0       anmol   12.0  90.000  21.000000
1        nama   11.0  56.000   3.000000
2      rajesh    5.0  50.625   4.000000
3       gauri    3.0  23.000   6.000000
4      keshav    5.0  45.000  20.666667
5       kapil    NaN  67.000  56.000000
6     srishti    8.0  50.625  34.000000
7     vaibhav    8.0  34.000   5.000000
8   dharmensh    NaN  34.000  23.000000
9        hari    7.0  50.625  34.000000
10     raghav    NaN  56.000  20.666667
11      suman    8.0  50.625  20.666667

13.	Removing Duplicates
o	Create a DataFrame containing duplicate student records.
o	Remove duplicate rows

In [ ]:
dataset2=pd.DataFrame({
    "name":["anmol", "anmol", "rajesh", "gauri", "keshav", "kapil", "srishti", "vaibhav", "dharmensh","hari", "raghav", "raghav"],
    "class":[12,12,5,3,5,None,8,8,None,7,None,None],
    "Marks":[90,90,None, 23, 45, 67, None, 34, 34, None,56,56],
    "Age": [21,21,4,6,None,56,34,5,23,34,None,None]
})
dataset2

         name  class  Marks   Age
0       anmol   12.0   90.0  21.0
1       anmol   12.0   90.0  21.0
2      rajesh    5.0    NaN   4.0
3       gauri    3.0   23.0   6.0
4      keshav    5.0   45.0   NaN
5       kapil    NaN   67.0  56.0
6     srishti    8.0    NaN  34.0
7     vaibhav    8.0   34.0   5.0
8   dharmensh    NaN   34.0  23.0
9        hari    7.0    NaN  34.0
10     raghav    NaN   56.0   NaN
11     raghav    NaN   56.0   NaN

In [ ]:
import pandas as pd

1.	Create a DataFrame
o	Create a DataFrame containing student names, roll numbers, branch, and marks.
o	Display the first 5 and last 5 records.

In [ ]:
df=pd.DataFrame({"name":["anmol","raghav","shyam","hari","gopal","hareesh","naman","krishna","suman"],
                 "roll_numbers":[3,5,6,8,7,4,7,8,6],
                 "branch":["cse","aiml","cse","aiml","mechanical","cse","aiml","mechanical","aiml"],
                 "marks":[45,23,42,45,34,45,56,56,67]})
df.head()

     name  roll_numbers      branch  marks
0   anmol             3         cse     45
1  raghav             5        aiml     23
2   shyam             6         cse     42
3    hari             8        aiml     45
4   gopal             7  mechanical     34

In [ ]:
df.tail()

      name  roll_numbers      branch  marks
4    gopal             7  mechanical     34
5  hareesh             4         cse     45
6    naman             7        aiml     56
7  krishna             8  mechanical     56
8    suman             6        aiml     67

2.	Series Operations
o	Create a Pandas Series containing marks of 10 students.
o	Find the maximum, minimum, mean, and median marks.

In [ ]:
marks=pd.Series([34,56,45,345,46,55,4,5,55,6])
marks,marks.max(),marks.mean(),marks.min(),marks.median()

(0     34
 1     56
 2     45
 3    345
 4     46
 5     55
 6      4
 7      5
 8     55
 9      6
 dtype: int64,
 np.int64(345),
 np.float64(65.1),
 np.int64(4),
 np.float64(45.5))

3.	DataFrame Information
o	Create a DataFrame with employee details.
o	Display its shape, columns, data types, and statistical summary.

In [ ]:
employee=pd.DataFrame({"e_id":[2,4,5,7,8,7,5,3,4,6],
                       "e_name":["a","b","c","d","e","f","g","h","i","j"],
                       "salary":[3400,5677,3556,6757,464,5566,4545,6768,4455,3434]})
employee

   e_id e_name  salary
0     2      a    3400
1     4      b    5677
2     5      c    3556
3     7      d    6757
4     8      e     464
5     7      f    5566
6     5      g    4545
7     3      h    6768
8     4      i    4455
9     6      j    3434

In [ ]:
employee.describe()

            e_id       salary
count  10.000000    10.000000
mean    5.100000  4462.200000
std     1.911951  1893.735509
min     2.000000   464.000000
25%     4.000000  3464.500000
50%     5.000000  4500.000000
75%     6.750000  5649.250000
max     8.000000  6768.000000

In [ ]:
employee.size

30

In [ ]:
employee.columns

Index(['e_id', 'e_name', 'salary'], dtype='object')

In [ ]:
employee.dtypes

e_id       int64
e_name    object
salary     int64
dtype: object

In [ ]:
employee.shape

(10, 3)

o	Given a student DataFrame, select only Name, Branch, and Marks columns.

In [ ]:
student = pd.DataFrame({
    "Roll_No": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
                111, 112, 113, 114, 115, 116, 117, 118, 119, 120],

    "Name": ["Anmol", "Rahul", "Priya", "Aman", "Neha",
             "Riya", "Karan", "Simran", "Arjun", "Pooja",
             "Vikas", "Sneha", "Rohit", "Kavya", "Yash",
             "Nisha", "Mohit", "Divya", "Harsh", "Isha"],

    "Age": [20, 21, 19, 22, 20,
            21, 23, 20, 22, 19,
            21, 20, 22, 23, 19,
            21, 20, 22, 23, 19],

    "Branch": ["CSE", "IT", "ECE", "ME", "CSE",
               "IT", "AIML", "ECE", "ME", "AIML",
               "CSE", "IT", "ECE", "ME", "AIML",
               "CSE", "IT", "ECE", "ME", "AIML"],

    "Semester": [3, 3, 2, 4, 3,
                 3, 5, 2, 4, 5,
                 4, 2, 3, 5, 4,
                 6, 5, 2, 4, 3],

    "Marks": [85, 78, 92, 67, 88,
              81, 95, 74, 69, 90,
              76, 84, 91, 73, 89,
              80, 94, 77, 68, 86],

    "City": ["Delhi", "Mathura", "Agra", "Noida", "Meerut",
             "Lucknow", "Kanpur", "Jaipur", "Gurgaon", "Pune",
             "Varanasi", "Patna", "Bhopal", "Indore", "Chandigarh",
             "Dehradun", "Surat", "Ahmedabad", "Mumbai", "Hyderabad"]
})

print(student)

    Roll_No    Name  Age Branch  Semester  Marks        City
0       101   Anmol   20    CSE         3     85       Delhi
1       102   Rahul   21     IT         3     78     Mathura
2       103   Priya   19    ECE         2     92        Agra
3       104    Aman   22     ME         4     67       Noida
4       105    Neha   20    CSE         3     88      Meerut
5       106    Riya   21     IT         3     81     Lucknow
6       107   Karan   23   AIML         5     95      Kanpur
7       108  Simran   20    ECE         2     74      Jaipur
8       109   Arjun   22     ME         4     69     Gurgaon
9       110   Pooja   19   AIML         5     90        Pune
10      111   Vikas   21    CSE         4     76    Varanasi
11      112   Sneha   20     IT         2     84       Patna
12      113   Rohit   22    ECE         3     91      Bhopal
13      114   Kavya   23     ME         5     73      Indore
14      115    Yash   19   AIML         4     89  Chandigarh
15      116   Nisha   21    CSE         6     80    Dehradun
16      117   Mohit   20     IT         5     94       Surat
17      118   Divya   22    ECE         2     77   Ahmedabad
18      119   Harsh   23     ME         4     68      Mumbai
19      120    Isha   19   AIML         3     86   Hyderabad

In [ ]:
print(student[["Name", "Marks","Branch"]])

      Name  Marks Branch
0    Anmol     85    CSE
1    Rahul     78     IT
2    Priya     92    ECE
3     Aman     67     ME
4     Neha     88    CSE
5     Riya     81     IT
6    Karan     95   AIML
7   Simran     74    ECE
8    Arjun     69     ME
9    Pooja     90   AIML
10   Vikas     76    CSE
11   Sneha     84     IT
12   Rohit     91    ECE
13   Kavya     73     ME
14    Yash     89   AIML
15   Nisha     80    CSE
16   Mohit     94     IT
17   Divya     77    ECE
18   Harsh     68     ME
19    Isha     86   AIML

5.	Selecting Rows
o	Extract the first 10 rows from index 5 to 15 using iloc.

In [ ]:
student.iloc[:10]

   Roll_No    Name  Age Branch  Semester  Marks     City
0      101   Anmol   20    CSE         3     85    Delhi
1      102   Rahul   21     IT         3     78  Mathura
2      103   Priya   19    ECE         2     92     Agra
3      104    Aman   22     ME         4     67    Noida
4      105    Neha   20    CSE         3     88   Meerut
5      106    Riya   21     IT         3     81  Lucknow
6      107   Karan   23   AIML         5     95   Kanpur
7      108  Simran   20    ECE         2     74   Jaipur
8      109   Arjun   22     ME         4     69  Gurgaon
9      110   Pooja   19   AIML         5     90     Pune

In [ ]:
student.iloc[5:16]

    Roll_No    Name  Age Branch  Semester  Marks        City
5       106    Riya   21     IT         3     81     Lucknow
6       107   Karan   23   AIML         5     95      Kanpur
7       108  Simran   20    ECE         2     74      Jaipur
8       109   Arjun   22     ME         4     69     Gurgaon
9       110   Pooja   19   AIML         5     90        Pune
10      111   Vikas   21    CSE         4     76    Varanasi
11      112   Sneha   20     IT         2     84       Patna
12      113   Rohit   22    ECE         3     91      Bhopal
13      114   Kavya   23     ME         5     73      Indore
14      115    Yash   19   AIML         4     89  Chandigarh
15      116   Nisha   21    CSE         6     80    Dehradun

6.	Using loc
o	Set the student roll number as the index.
o	Select students with specific roll numbers using loc.

In [ ]:
student.loc[]

SyntaxError: invalid syntax (558123738.py, line 1)

7.	Filtering Data
o	Find all students who scored more than 75 marks.

In [ ]:
student[student["Marks"] > 75]

    Roll_No   Name  Age Branch  Semester  Marks        City
0       101  Anmol   20    CSE         3     85       Delhi
1       102  Rahul   21     IT         3     78     Mathura
2       103  Priya   19    ECE         2     92        Agra
4       105   Neha   20    CSE         3     88      Meerut
5       106   Riya   21     IT         3     81     Lucknow
6       107  Karan   23   AIML         5     95      Kanpur
9       110  Pooja   19   AIML         5     90        Pune
10      111  Vikas   21    CSE         4     76    Varanasi
11      112  Sneha   20     IT         2     84       Patna
12      113  Rohit   22    ECE         3     91      Bhopal
14      115   Yash   19   AIML         4     89  Chandigarh
15      116  Nisha   21    CSE         6     80    Dehradun
16      117  Mohit   20     IT         5     94       Surat
17      118  Divya   22    ECE         2     77   Ahmedabad
19      120   Isha   19   AIML         3     86   Hyderabad

8.	Multiple Conditions
o	Find students from the CSE branch who scored more than 80.

In [ ]:
student[(student["Marks"]>80) & (student["Branch"]== "CSE")]

   Roll_No   Name  Age Branch  Semester  Marks    City
0      101  Anmol   20    CSE         3     85   Delhi
4      105   Neha   20    CSE         3     88  Meerut

9.	Adding a Column
o	Add a Result column based on marks:
	Marks ≥ 40 → Pass
	Marks < 40 → Fail

In [ ]:
student["Grade"] = ""
student.loc[student["Marks"]>=80, "Grade"] = "Pass"
student.loc[student["Marks"]<80, "Grade"]= "Fail"

In [ ]:
student

    Roll_No    Name  Age Branch  Semester  Marks        City Grade
0       101   Anmol   20    CSE         3     85       Delhi  Pass
1       102   Rahul   21     IT         3     78     Mathura  Fail
2       103   Priya   19    ECE         2     92        Agra  Pass
3       104    Aman   22     ME         4     67       Noida  Fail
4       105    Neha   20    CSE         3     88      Meerut  Pass
5       106    Riya   21     IT         3     81     Lucknow  Pass
6       107   Karan   23   AIML         5     95      Kanpur  Pass
7       108  Simran   20    ECE         2     74      Jaipur  Fail
8       109   Arjun   22     ME         4     69     Gurgaon  Fail
9       110   Pooja   19   AIML         5     90        Pune  Pass
10      111   Vikas   21    CSE         4     76    Varanasi  Fail
11      112   Sneha   20     IT         2     84       Patna  Pass
12      113   Rohit   22    ECE         3     91      Bhopal  Pass
13      114   Kavya   23     ME         5     73      Indore  Fail
14      115    Yash   19   AIML         4     89  Chandigarh  Pass
15      116   Nisha   21    CSE         6     80    Dehradun  Pass
16      117   Mohit   20     IT         5     94       Surat  Pass
17      118   Divya   22    ECE         2     77   Ahmedabad  Fail
18      119   Harsh   23     ME         4     68      Mumbai  Fail
19      120    Isha   19   AIML         3     86   Hyderabad  Pass

In [ ]:
descending=student.sort_values(by="Marks", ascending=False)
descending.head()

    Roll_No   Name  Age Branch  Semester  Marks    City Grade
6       107  Karan   23   AIML         5     95  Kanpur  Pass
16      117  Mohit   20     IT         5     94   Surat  Pass
2       103  Priya   19    ECE         2     92    Agra  Pass
12      113  Rohit   22    ECE         3     91  Bhopal  Pass
9       110  Pooja   19   AIML         5     90    Pune  Pass

11.	Missing Values
o	Create a DataFrame containing missing values.
o	Identify missing values using isnull() and isna().
12.	Handling Missing Values
o	Replace missing numerical values with the column mean.

In [ ]:
students = pd.DataFrame({
    "Name": ["Anmol", "Rahul", "Priya", "Aman", "Neha"],
    "Marks": [85, 72, None, 91, None],
    "Age": [20, None, 19, 21, None],
    "City": ["Mathura", "Delhi", None, "Agra", "Meerut"]
})

print(students)

    Name  Marks   Age     City
0  Anmol   85.0  20.0  Mathura
1  Rahul   72.0   NaN    Delhi
2  Priya    NaN  19.0     None
3   Aman   91.0  21.0     Agra
4   Neha    NaN   NaN   Meerut

In [ ]:
students.isnull()

    Name  Marks    Age   City
0  False  False  False  False
1  False  False   True  False
2  False   True  False   True
3  False  False  False  False
4  False   True   True  False

In [ ]:
students.isna()

    Name  Marks    Age   City
0  False  False  False  False
1  False  False   True  False
2  False   True  False   True
3  False  False  False  False
4  False   True   True  False

In [ ]:
students.fillna({
    "Marks": students["Marks"].mean(),
    "Age": students["Age"].mean()
    
})

    Name      Marks   Age     City
0  Anmol  85.000000  20.0  Mathura
1  Rahul  72.000000  20.0    Delhi
2  Priya  82.666667  19.0     None
3   Aman  91.000000  21.0     Agra
4   Neha  82.666667  20.0   Meerut

14.	Rename Columns
o	Rename Student_Name to Name and Student_Marks to Marks.

In [ ]:
students.rename(columns={
    "Marks": "Student_marks",
    "Age":"students_age"
})

    Name  Student_marks  students_age     City
0  Anmol           85.0          20.0  Mathura
1  Rahul           72.0           NaN    Delhi
2  Priya            NaN          19.0     None
3   Aman           91.0          21.0     Agra
4   Neha            NaN           NaN   Meerut

15.	Export and Import
o	Save a DataFrame as a CSV file.
o	Read the CSV file back into Pandas.

In [ ]:
students.to_csv("students.csv",index=False)

In [ ]:
pd.read_csv("students.csv")

    Name  Student_marks  students_age     City
0  Anmol           85.0          20.0  Mathura
1  Rahul           72.0           NaN    Delhi
2  Priya            NaN          19.0      NaN
3   Aman           91.0          21.0     Agra
4   Neha            NaN           NaN   Meerut

16.	GroupBy – Average Marks
o	Given student data containing Branch and Marks, calculate the average marks for each branch.

In [ ]:
student

    Name  Marks   Age     City
0  Anmol   85.0  20.0  Mathura
1  Rahul   72.0   NaN    Delhi
2  Priya    NaN  19.0     None
3   Aman   91.0  21.0     Agra
4   Neha    NaN   NaN   Meerut

In [ ]:
student.groupby("Branch")["Marks"].mean()

Branch
AIML    90.00
CSE     82.25
ECE     83.50
IT      84.25
ME      69.25
Name: Marks, dtype: float64

17.	GroupBy – Multiple Aggregations
o	Find the minimum, maximum, average, and standard deviation of marks for each branch.

In [ ]:
student.groupby("Branch")["Marks"].agg(["mean", "max", "min","std", "median", "size"])

         mean  max  min       std  median  size
Branch
AIML    90.00   95   86  3.741657    89.5     4
CSE     82.25   88   76  5.315073    82.5     4
ECE     83.50   92   74  9.327379    84.0     4
IT      84.25   94   78  6.946222    82.5     4
ME      69.25   73   67  2.629956    68.5     4

18.	Value Counts
o	Given a dataset of student branches, count the number of students in each branch.

In [ ]:
student.groupby("Branch").count()

        Roll_No  Name  Age  Semester  Marks  City  Grade
Branch
AIML          4     4    4         4      4     4      4
CSE           4     4    4         4      4     4      4
ECE           4     4    4         4      4     4      4
IT            4     4    4         4      4     4      4
ME            4     4    4         4      4     4      4

19.	Conditional Column
o	Cre	F: < 40
ate a Grade column:
	A: ≥ 90
	B: 75–89
	C: 60–74
	D: 40–59

In [ ]:
student["Grade"] = ""
student.loc[student["Marks"]>=90, "Grade"]="A"
student.loc[(student["Marks"]>=75) & (student["Marks"]<=89) , "Grade"]= "B" 
student.loc[(student["Marks"]>=60) & (student["Marks"]<=74), "Grade"]="C"
student.loc[(student["Marks"]>=40)&(student["Marks"]<59), "Grade"]="D"
student.loc[(student["Marks"]<40), "Grade"]="F"

In [ ]:
student

    Roll_No    Name  Age Branch  Semester  Marks        City  percentage
0       101   Anmol   20    CSE         3    450       Delhi        90.0
1       102   Rahul   21     IT         3    348     Mathura        69.6
2       103   Priya   19    ECE         2   2462        Agra       492.4
3       104    Aman   22     ME         4    467       Noida        93.4
4       105    Neha   20    CSE         3    388      Meerut        77.6
5       106    Riya   21     IT         3    345     Lucknow        69.0
6       107   Karan   23   AIML         5    235      Kanpur        47.0
7       108  Simran   20    ECE         2    244      Jaipur        48.8
8       109   Arjun   22     ME         4    329     Gurgaon        65.8
9       110   Pooja   19   AIML         5    490        Pune        98.0
10      111   Vikas   21    CSE         4    276    Varanasi        55.2
11      112   Sneha   20     IT         2    284       Patna        56.8
12      113   Rohit   22    ECE         3    391      Bhopal        78.2
13      114   Kavya   23     ME         5    473      Indore        94.6
14      115    Yash   19   AIML         4     89  Chandigarh        17.8
15      116   Nisha   21    CSE         6    480    Dehradun        96.0
16      117   Mohit   20     IT         5    394       Surat        78.8
17      118   Divya   22    ECE         2    377   Ahmedabad        75.4
18      119   Harsh   23     ME         4    268      Mumbai        53.6
19      120    Isha   19   AIML         3    186   Hyderabad        37.2

20.	Apply Function
o	Use the apply() function to calculate the percentage of students based on marks obtained out of 500.

In [ ]:
student1 = pd.DataFrame({
    "Name": ["Anmol", "Rahul", "Aman", "Priya", "Riya", "Karan", "Neha", "Arjun"],
    "Branch": ["CSE", "AIML", "CSE", "AIML", "CSE", "AIML", "CSE", "AIML"],
    "Marks": [450, 380, 425, 310, 275, 490, 350, 225]
})

print(student1)

    Name Branch  Marks
0  Anmol    CSE    450
1  Rahul   AIML    380
2   Aman    CSE    425
3  Priya   AIML    310
4   Riya    CSE    275
5  Karan   AIML    490
6   Neha    CSE    350
7  Arjun   AIML    225

In [ ]:
student1["percentage"]= student1["Marks"].apply(
    lambda x:(x/500)*100
)

In [ ]:
student1

    Name Branch  Marks  percentage
0  Anmol    CSE    450        90.0
1  Rahul   AIML    380        76.0
2   Aman    CSE    425        85.0
3  Priya   AIML    310        62.0
4   Riya    CSE    275        55.0
5  Karan   AIML    490        98.0
6   Neha    CSE    350        70.0
7  Arjun   AIML    225        45.0

21.	String Operations
o	Given student names, convert all names to uppercase.
o	Extract the first letter of each name.

In [ ]:
student["Name"]=student["Name"].str.capitalize()

In [ ]:
student

    Roll_No    Name  Age Branch  Semester  Marks        City  percentage
0       101   Anmol   20    CSE         3     85       Delhi        17.0
1       102   Rahul   21     IT         3     78     Mathura        15.6
2       103   Priya   19    ECE         2     92        Agra        18.4
3       104    Aman   22     ME         4     67       Noida        13.4
4       105    Neha   20    CSE         3     88      Meerut        17.6
5       106    Riya   21     IT         3     81     Lucknow        16.2
6       107   Karan   23   AIML         5     95      Kanpur        19.0
7       108  Simran   20    ECE         2     74      Jaipur        14.8
8       109   Arjun   22     ME         4     69     Gurgaon        13.8
9       110   Pooja   19   AIML         5     90        Pune        18.0
10      111   Vikas   21    CSE         4     76    Varanasi        15.2
11      112   Sneha   20     IT         2     84       Patna        16.8
12      113   Rohit   22    ECE         3     91      Bhopal        18.2
13      114   Kavya   23     ME         5     73      Indore        14.6
14      115    Yash   19   AIML         4     89  Chandigarh        17.8
15      116   Nisha   21    CSE         6     80    Dehradun        16.0
16      117   Mohit   20     IT         5     94       Surat        18.8
17      118   Divya   22    ECE         2     77   Ahmedabad        15.4
18      119   Harsh   23     ME         4     68      Mumbai        13.6
19      120    Isha   19   AIML         3     86   Hyderabad        17.2

In [ ]:
student["First_letter"]=student["Name"].str[0]

In [ ]:
student["First_letter"]

0     A
1     R
2     P
3     A
4     N
5     R
6     K
7     S
8     A
9     P
10    V
11    S
12    R
13    K
14    Y
15    N
16    M
17    D
18    H
19    I
Name: First_letter, dtype: object

22.	DateTime Operations
o	Create a DataFrame containing employee joining dates.
o	Extract year, month, and day from the joining date.

In [ ]:


employee = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Anmol Gola", "Rahul Sharma", "Aman Verma", "Priya Singh",
             "Riya Gupta", "Karan Mehta", "Neha Kapoor", "Arjun Yadav"],
    "Department": ["IT", "HR", "Finance", "IT", "Marketing", "HR", "Finance", "IT"],
    "Joining_Date": [
        "2022-06-15",
        "2021-03-20",
        "2023-01-10",
        "2020-11-05",
        "2022-08-25",
        "2024-02-12",
        "2021-09-18",
        "2023-07-01"
    ],
    "Salary": [55000, 48000, 62000, 70000, 50000, 45000, 58000, 65000],
    "Experience": [6, 7, 3, 8, 5, 2, 7, 4]
})

print(employee)

   Employee_ID          Name Department Joining_Date  Salary  Experience
0          101    Anmol Gola         IT   2022-06-15   55000           6
1          102  Rahul Sharma         HR   2021-03-20   48000           7
2          103    Aman Verma    Finance   2023-01-10   62000           3
3          104   Priya Singh         IT   2020-11-05   70000           8
4          105    Riya Gupta  Marketing   2022-08-25   50000           5
5          106   Karan Mehta         HR   2024-02-12   45000           2
6          107   Neha Kapoor    Finance   2021-09-18   58000           7
7          108   Arjun Yadav         IT   2023-07-01   65000           4

In [ ]:
pd.to_datetime(employee["Joining_Date"])

0   2022-06-15
1   2021-03-20
2   2023-01-10
3   2020-11-05
4   2022-08-25
5   2024-02-12
6   2021-09-18
7   2023-07-01
Name: Joining_Date, dtype: datetime64[ns]

In [ ]:
month=employee["Joining_Date"].dt.month
year=employee["Joining_Date"].dt.year
date=employee["Joining_Date"].dt.date
print(month,date,year)

0     6
1     3
2     1
3    11
4     8
5     2
6     9
7     7
Name: Joining_Date, dtype: int32 0    2022-06-15
1    2021-03-20
2    2023-01-10
3    2020-11-05
4    2022-08-25
5    2024-02-12
6    2021-09-18
7    2023-07-01
Name: Joining_Date, dtype: object 0    2022
1    2021
2    2023
3    2020
4    2022
5    2024
6    2021
7    2023
Name: Joining_Date, dtype: int32

23.	Filtering with query()
o	Use query() to find employees whose salary is greater than $50,000 and experience is greater than 5 years.

In [ ]:
result=employee.query("Salary>50000 and Experience >5")
print(result)

   Employee_ID         Name Department Joining_Date  Salary  Experience
0          101   Anmol Gola         IT   2022-06-15   55000           6
3          104  Priya Singh         IT   2020-11-05   70000           8
6          107  Neha Kapoor    Finance   2021-09-18   58000           7

In [ ]:


student_info = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Anmol", "Rahul", "Aman", "Priya", "Riya", "Karan"],
    "Branch": ["CSE", "AIML", "CSE", "AIML", "CSE", "AIML"],
    "Age": [19, 20, 19, 20, 18, 21]
})

print(student_info)

   Student_ID   Name Branch  Age
0         101  Anmol    CSE   19
1         102  Rahul   AIML   20
2         103   Aman    CSE   19
3         104  Priya   AIML   20
4         105   Riya    CSE   18
5         106  Karan   AIML   21

In [ ]:
exam_result = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104, 105, 106],
    "Maths": [85, 78, 92, 88, 75, 69],
    "Python": [90, 82, 88, 91, 79, 72],
    "Data_Science": [87, 80, 94, 85, 81, 70]
})

print(exam_result)

   Student_ID  Maths  Python  Data_Science
0         101     85      90            87
1         102     78      82            80
2         103     92      88            94
3         104     88      91            85
4         105     75      79            81
5         106     69      72            70

In [ ]:
pd.merge(student_info, exam_result, on="Student_ID")

   Student_ID   Name Branch  Age  Maths  Python  Data_Science
0         101  Anmol    CSE   19     85      90            87
1         102  Rahul   AIML   20     78      82            80
2         103   Aman    CSE   19     92      88            94
3         104  Priya   AIML   20     88      91            85
4         105   Riya    CSE   18     75      79            81
5         106  Karan   AIML   21     69      72            70

26.	Join DataFrames
o	Perform inner, left, right, and outer joins on two DataFrames.
o	Compare the resulting records.

In [ ]:
pd.merge(student_info, exam_result, on="Student_ID", how="inner")

   Student_ID   Name Branch  Age  Maths  Python  Data_Science
0         101  Anmol    CSE   19     85      90            87
1         102  Rahul   AIML   20     78      82            80
2         103   Aman    CSE   19     92      88            94
3         104  Priya   AIML   20     88      91            85
4         105   Riya    CSE   18     75      79            81
5         106  Karan   AIML   21     69      72            70

In [ ]:
pd.merge(student_info, exam_result, on="Student_ID", how="outer")

   Student_ID   Name Branch  Age  Maths  Python  Data_Science
0         101  Anmol    CSE   19     85      90            87
1         102  Rahul   AIML   20     78      82            80
2         103   Aman    CSE   19     92      88            94
3         104  Priya   AIML   20     88      91            85
4         105   Riya    CSE   18     75      79            81
5         106  Karan   AIML   21     69      72            70

In [ ]:
pd.merge(student_info, exam_result, on="Student_ID", how="right")

   Student_ID   Name Branch  Age  Maths  Python  Data_Science
0         101  Anmol    CSE   19     85      90            87
1         102  Rahul   AIML   20     78      82            80
2         103   Aman    CSE   19     92      88            94
3         104  Priya   AIML   20     88      91            85
4         105   Riya    CSE   18     75      79            81
5         106  Karan   AIML   21     69      72            70

In [ ]:
pd.merge(student_info, exam_result, on="Student_ID", how ="left")

   Student_ID   Name Branch  Age  Maths  Python  Data_Science
0         101  Anmol    CSE   19     85      90            87
1         102  Rahul   AIML   20     78      82            80
2         103   Aman    CSE   19     92      88            94
3         104  Priya   AIML   20     88      91            85
4         105   Riya    CSE   18     75      79            81
5         106  Karan   AIML   21     69      72            70

    concatenation
	Create separate DataFrames for students from different semesters.

In [ ]:
import pandas as pd

sem1 = pd.DataFrame({
    "Student_ID": [101, 102, 103],
    "Name": ["Anmol", "Rahul", "Aman"],
    "Branch": ["CSE", "AIML", "CSE"],
    "Marks": [85, 78, 90]
})
sem1

   Student_ID   Name Branch  Marks
0         101  Anmol    CSE     85
1         102  Rahul   AIML     78
2         103   Aman    CSE     90

In [ ]:
sem2 = pd.DataFrame({
    "Student_ID": [104, 105, 106],
    "Name": ["Priya", "Riya", "Karan"],
    "Branch": ["AIML", "CSE", "AIML"],
    "Marks": [82, 88, 75]
})
sem2

   Student_ID   Name Branch  Marks
0         104  Priya   AIML     82
1         105   Riya    CSE     88
2         106  Karan   AIML     75

In [ ]:
sem3 = pd.DataFrame({
    "Student_ID": [107, 108, 109],
    "Name": ["Neha", "Arjun", "Simran"],
    "Branch": ["CSE", "AIML", "CSE"],
    "Marks": [92, 80, 87]
})
sem3

   Student_ID    Name Branch  Marks
0         107    Neha    CSE     92
1         108   Arjun   AIML     80
2         109  Simran    CSE     87

In [ ]:
all_sem_data = pd.concat([sem1, sem2, sem3],ignore_index=True)

In [ ]:
all_sem_data

   Student_ID    Name Branch  Marks  Semester
0         101   Anmol    CSE     85         1
1         102   Rahul   AIML     78         1
2         103    Aman    CSE     90         1
3         104   Priya   AIML     82         2
4         105    Riya    CSE     88         2
5         106   Karan   AIML     75         2
6         107    Neha    CSE     92         3
7         108   Arjun   AIML     80         3
8         109  Simran    CSE     87         3

28.	Pivot Table
o	Given sales data containing Employee, Product, Region, and Sales, create a pivot table showing total sales by region and product.

In [ ]:
import pandas as pd

sales = pd.DataFrame({
    "Employee": ["Anmol", "Rahul", "Aman", "Priya", "Riya",
                 "Karan", "Neha", "Arjun", "Simran", "Vivek"],
    "Product": ["Laptop", "Phone", "Laptop", "Tablet", "Phone",
                "Laptop", "Tablet", "Phone", "Laptop", "Tablet"],
    "Region": ["North", "South", "North", "East", "South",
               "West", "East", "West", "North", "South"],
    "Sales": [50000, 30000, 45000, 25000, 35000,
              60000, 28000, 32000, 55000, 22000]
})

print(sales)

  Employee Product Region  Sales
0    Anmol  Laptop  North  50000
1    Rahul   Phone  South  30000
2     Aman  Laptop  North  45000
3    Priya  Tablet   East  25000
4     Riya   Phone  South  35000
5    Karan  Laptop   West  60000
6     Neha  Tablet   East  28000
7    Arjun   Phone   West  32000
8   Simran  Laptop  North  55000
9    Vivek  Tablet  South  22000

In [ ]:
pivot=pd.pivot_table(
    sales,
    values="Sales",
    index="Region",
    columns="Product",
    aggfunc="sum",
    fill_value=0  #replces nan with 0
)
print(pivot)

Product  Laptop  Phone  Tablet
Region
East          0      0   53000
North    150000      0       0
South         0  65000   22000
West      60000  32000       0

29.	Ranking
o	Rank students based on their marks.
o	Assign rank 1 to the highest-scoring student.

In [ ]:
student

,Roll_No,Name,Age,Branch,Semester,Marks,City,percentage,First_letter
0,101,Anmol,20,CSE,3,85,Delhi,17.0,A
1,102,Rahul,21,IT,3,78,Mathura,15.6,R
2,103,Priya,19,ECE,2,92,Agra,18.4,P
3,104,Aman,22,ME,4,67,Noida,13.4,A
4,105,Neha,20,CSE,3,88,Meerut,17.6,N
5,106,Riya,21,IT,3,81,Lucknow,16.2,R
6,107,Karan,23,AIML,5,95,Kanpur,19.0,K
7,108,Simran,20,ECE,2,74,Jaipur,14.8,S
8,109,Arjun,22,ME,4,69,Gurgaon,13.8,A
9,110,Pooja,19,AIML,5,90,Pune,18.0,P
10,111,Vikas,21,CSE,4,76,Varanasi,15.2,V
11,112,Sneha,20,IT,2,84,Patna,16.8,S
12,113,Rohit,22,ECE,3,91,Bhopal,18.2,R
13,114,Kavya,23,ME,5,73,Indore,14.6,K
14,115,Yash,19,AIML,4,89,Chandigarh,17.8,Y
15,116,Nisha,21,CSE,6,80,Dehradun,16.0,N
16,117,Mohit,20,IT,5,94,Surat,18.8,M
17,118,Divya,22,ECE,2,77,Ahmedabad,15.4,D
18,119,Harsh,23,ME,4,68,Mumbai,13.6,H
19,120,Isha,19,AIML,3,86,Hyderabad,17.2,I

In [ ]:
student["Rank"] = student["Marks"].rank(ascending=False)

In [ ]:
student

,Roll_No,Name,Age,Branch,Semester,Marks,City,percentage,First_letter,Rank
0,101,Anmol,20,CSE,3,85,Delhi,17.0,A,9.0
1,102,Rahul,21,IT,3,78,Mathura,15.6,R,13.0
2,103,Priya,19,ECE,2,92,Agra,18.4,P,3.0
3,104,Aman,22,ME,4,67,Noida,13.4,A,20.0
4,105,Neha,20,CSE,3,88,Meerut,17.6,N,7.0
5,106,Riya,21,IT,3,81,Lucknow,16.2,R,11.0
6,107,Karan,23,AIML,5,95,Kanpur,19.0,K,1.0
7,108,Simran,20,ECE,2,74,Jaipur,14.8,S,16.0
8,109,Arjun,22,ME,4,69,Gurgaon,13.8,A,18.0
9,110,Pooja,19,AIML,5,90,Pune,18.0,P,5.0
10,111,Vikas,21,CSE,4,76,Varanasi,15.2,V,15.0
11,112,Sneha,20,IT,2,84,Patna,16.8,S,10.0
12,113,Rohit,22,ECE,3,91,Bhopal,18.2,R,4.0
13,114,Kavya,23,ME,5,73,Indore,14.6,K,17.0
14,115,Yash,19,AIML,4,89,Chandigarh,17.8,Y,6.0
15,116,Nisha,21,CSE,6,80,Dehradun,16.0,N,12.0
16,117,Mohit,20,IT,5,94,Surat,18.8,M,2.0
17,118,Divya,22,ECE,2,77,Ahmedabad,15.4,D,14.0
18,119,Harsh,23,ME,4,68,Mumbai,13.6,H,19.0
19,120,Isha,19,AIML,3,86,Hyderabad,17.2,I,8.0

30.	Top-N Analysis
o	Find the top 3 students from each branch based on marks.

In [ ]:
student.groupby("Branch")["Marks"].nlargest(3)

Branch
AIML    6     95
        9     90
        14    89
CSE     4     88
        0     85
        15    80
ECE     2     92
        12    91
        17    77
IT      16    94
        11    84
        5     81
ME      13    73
        8     69
        18    68
Name: Marks, dtype: int64

In [ ]:
top3 = (
    student
    .sort_values(["Branch", "Marks"], ascending=[True, False])
    .groupby("Branch")
    .head(3)
)

print(top3)

    Roll_No   Name  Age Branch  Semester  Marks        City  percentage  \
6       107  Karan   23   AIML         5     95      Kanpur        19.0
9       110  Pooja   19   AIML         5     90        Pune        18.0
14      115   Yash   19   AIML         4     89  Chandigarh        17.8
4       105   Neha   20    CSE         3     88      Meerut        17.6
0       101  Anmol   20    CSE         3     85       Delhi        17.0
15      116  Nisha   21    CSE         6     80    Dehradun        16.0
2       103  Priya   19    ECE         2     92        Agra        18.4
12      113  Rohit   22    ECE         3     91      Bhopal        18.2
17      118  Divya   22    ECE         2     77   Ahmedabad        15.4
16      117  Mohit   20     IT         5     94       Surat        18.8
11      112  Sneha   20     IT         2     84       Patna        16.8
5       106   Riya   21     IT         3     81     Lucknow        16.2
13      114  Kavya   23     ME         5     73      Indore        14.6
8       109  Arjun   22     ME         4     69     Gurgaon        13.8
18      119  Harsh   23     ME         4     68      Mumbai        13.6

   First_letter  Rank
6             K   1.0
9             P   5.0
14            Y   6.0
4             N   7.0
0             A   9.0
15            N  12.0
2             P   3.0
12            R   4.0
17            D  14.0
16            M   2.0
11            S  10.0
5             R  11.0
13            K  17.0
8             A  18.0
18            H  19.0

31.	Group-Based Filtering
o	Find branches where the average student marks are greater than 70.

In [ ]:
avg_marks=student.groupby["Branch"]("Marks").mean()
result

0      CSE
1       IT
2      ECE
4      CSE
5       IT
6     AIML
7      ECE
9     AIML
10     CSE
11      IT
12     ECE
13      ME
14    AIML
15     CSE
16      IT
17     ECE
19    AIML
Name: Branch, dtype: object

: